"""Adding github login

Revision ID: f728996700c2
Revises: da62ff7d82cc
Create Date: 2021-03-19 18:29:36.325255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f728996700c2"
down_revision = "da62ff7d82cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=80), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=80), nullable=False
    )
    # ### end Alembic commands ###
